language: generic
os:
  - linux
  - osx
sudo: required
services:
  - docker

before_install:
  - bash -e ci/travis_before_install.sh
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export TARGET_NAME=darwin-x64; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export TARGET_NAME=linux-x64; fi

before_script:
  - IS_GRAPHQL_PPX_CI=true yarn
  - "./ci/before_script_$TRAVIS_OS_NAME.sh"

script:
  - "./ci/build_script_$TRAVIS_OS_NAME.sh"
  - make only-test TARGET_BUCKLESCRIPT=1
  - NODE_ENV=production make only-test TARGET_BUCKLESCRIPT=1
  - mv graphql_ppx.exe graphql_ppx-$TARGET_NAME.exe

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: graphql_ppx-*.exe
  api_key:
    secure: $GH_TOKEN
  on:
    tags: true
    repo: baransu/graphql_ppx
    branch: release

jobs:
  include:
    - stage: Wait for binaries to become available
      addons:
        apt:
          sources: []
          packages: []
      before_install: skip
      before_script: skip
      deploy: []
      script: bash -e ci/wait_for_builds.sh

    - stage: Deploy to npmjs
      addons:
        apt:
          sources: []
          packages: []
      before_install: skip
      before_script: skip
      script:
        - bash -e ci/download_binaries.sh

      deploy:
        provider: npm
        email: tomaszcichocinski@gmail.com
        skip_cleanup: true
        api_key:
          secure: nXJwd55igA9oCipVoE3MIRVyBZRqSd4P40jvAgh+Gq760pcrCMok48COLDH2VylFlzBtdqnK5c9x3iypZAx7hnEIQzAfj6DEeUakNjvk5tqJqUawGs8yEhGLlj28eqQribvL92fXp5rgFvDWNOddFgV7H9fXowdYKy4tg31ikkzOO7iEP3/9UTE9BCgkyOqY3TNz5ST/qhyf9aANhdavJymmSrM8W7x2IWxvzAR1R7q4yTn6jXqtqwdNOURCvl9rP8EhMWrUBi9yXTv2MbJocMxbw3Yy0xPcATOWipor1U5+4cfd+N5Ezbkn5uC7/FDmR2mXuOliA9ttjPx5IQoC4TWL/Ra82ZVBVSGVlDXBhHC7K/DGmELqwUs6G8kfsir3zZk4bhREplvxpCDrGaO9s91x9Svxpi9VgEA96v1ENCpbmXSZ9js+k7CIo9njTWDkkmIn7G/0giQdd25OtuF0+2DmSQHyYtfNlCISCl22q1HOd6VjyG9NFEKCNRmAPGe89oHrxl3OLWkh7ZLRAhTN/H9lDxYHzaeLK/Oyc9voxfUbzA3GFaNDr69+Fmczw+6rjxLT21Ig/CFAEN64a2AuFUIEJ6iGu6L+1U850dSHrP+ee7VIUZdxxWfMzS6Zf0uKGtBL3wyRt1dXiklWlJlBXdy4OAwqYsSJP80ebvoxKH0=
        on:
          tags: true
          repo: baransu/graphql_ppx
          branch: release
